### ISSUE TITLE
Stacked items

### ISSUE THREAD

**Issue by aloisdeniel** [letsar/overflow_view#1]
It would be great to have a "stack" mode too!

![image](https://user-images.githubusercontent.com/7687231/92388593-d814b900-f117-11ea-8d7f-83def9113262.png)

**Comment by letsar** [comment]
Oh great idea! I love it! How would you see it?
A OverflowView.stacked constructor with an overlapRatio (between 0 and 1) parameter or an overlap parameter taking an amount of pixel ?
All the items should be the same size or not (including the overflow indicator)?

**Comment by aloisdeniel** [comment]
Yes, the `OverflowView.stacked` seems good. With a `mainAxisOverlap` property in pixels would be enough in my opinion.

In my case all items are on the same size, but it would be great to have both options too. :)

![image](https://user-images.githubusercontent.com/7687231/92390181-ae10c600-f11a-11ea-885b-4191779adb08.png)

**Comment by letsar** [comment]
Hmm the algorithm for items with different sizes is totally different and less performant than the other one. If we want the two options, it may be better to just add the mainAxisOverlap to OverflowView and OverflowView.flexible constructor. But now I'm thinking about removing the assert on spacing parameter and make sure the items are painted in the right order.

**Comment by letsar** [comment]
Added in v0.2.1. You can now set a negative spacing to achieve the desired effect.

**Comment by aloisdeniel** [comment]
Perfect, thanks!
